package com.es.projector.ui.forms;

import com.es.projector.common.ImageManipulator;
import com.es.projector.net.rmi.ContentObserver;
import com.es.projector.net.rmi.ShareService;

import javax.swing.*;
import java.awt.*;
import java.awt.image.BufferedImage;

public class ScreenShare implements ContentObserver.ContentObserverListener {
    private JPanel mainPanel;
    private JLabel screenView;

    private ShareService shareService;
    private ContentObserver contentObserver;

    public ScreenShare(ShareService shareService) {
        this.shareService = shareService;
    }

    public JPanel getMainPanel() {
        return mainPanel;
    }

    public void observeStream() {
        this.contentObserver = new ContentObserver(this.shareService, this);
        this.contentObserver.start();
    }

    @Override
    public void onFrameUpdate(BufferedImage image) {
        BufferedImage resized = ImageManipulator.resizeWithScaling
                (image, mainPanel.getSize().width, mainPanel.getSize().height);
        screenView.setIcon(new ImageIcon(resized));
    }

    @Override
    public void onError(String error, boolean shouldClose) {
        JOptionPane.showMessageDialog(null, error);
        if (shouldClose) {
            System.exit(0);
        }
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBackground(new Color(-1));
        screenView = new JLabel();
        screenView.setHorizontalAlignment(0);
        screenView.setText("");
        mainPanel.add(screenView, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
